name: Generate Documentation

on:
  push:
    branches:
      - master
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run documentation generation script
        run: |
          output="REAMDE.md"
          echo "# Documentação dos Scripts" > "$output"

          for script in *.sh; do
            # Ignora o script generate_docs.sh
          #  if [[ "$script" == "generate_docs.sh" ]]; then
          #    continue
          #  fi

            echo "## $(basename "$script")" >> "$output"
            grep '^#' "$script" | sed 's/^# //' >> "$output"
            echo -e "\n---\n" >> "$output"
          done

          echo "Documentação gerada em $output."
          #wget https://raw.githubusercontent.com/UlissesRibeiro/documentoso/refs/heads/main/generate_docs.sh
          #chmod +x generate_docs.sh
          #./generate_docs.sh
      - name: Commit and push documentation
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

